#!/bin/sh
bindir=`dirname $0`
rootdir=$1
[ -f ${rootdir}/etc/centos-release -o -f ${rootdir}/etc/redhat-release ] || exit 1
rootdir=`cd ${rootdir};pwd`
shift
echo yum --installroot=${rootdir} "$@"
yum --nogpgcheck --installroot=${rootdir} "$@"
